### ISSUE TITLE
Utility functions for commonly occurring problems

### ISSUE THREAD

**Issue by eozd** [genbattle/dkm#1]
First of all, I would like to thank you for your work implementing dkm. I have used it in one of my projects and it was a breeze to set up and use.

During the time I was in the process of incorporating dkm into the project, I have written several utility functions that helped me use the library more efficiently. Currently, I have functions to
- calculate distance of each point to cluster center
- calculate sum of distances of each point to cluster center
- return all points that belong to the given cluster
- calculate the inertia of a given clustering using sum of distances method
- return the best clustering based on inertia
- calculate kmeans by running dkm::kmeans_lloyd function a given number of times and return the best clustering

Would you like me to send a pull request with these functions added to **dkm.hpp** file under a **util** namespace?

P.S.: All the functions are template functions; so the library would still be header-only.

**Comment by genbattle** [comment]
Hi there,

I'm glad you've found my little library useful. I'm certainly open to pull requests that improve this library.

Overall these sound like really good changes, but I'd love to see them in a separate header for utilities (e.g. `dkm_utils.hpp`), at least where feasible. The first two will be better off in the main header. Don't worry about creating a new namespace for the utilities, just use the main `dkm` namespace.

I look forward to reviewing your pull request :)
