### ISSUE TITLE
Is all the source code in include?

### ISSUE THREAD

**Issue by muzammil360** [genbattle/dkm#10]
Hi. it seems that you wrote a templatized version. 

I am assuming that all the library source code (for Kmeans) is in `include` folder and opencv is only required for an example. Further, we don't need openMP if we don't intend to use parallel version. And I am thinking about building it with VS2015 so won't need CMAKE either. 

Are my assumptions correct?

**Comment by genbattle** [comment]
Yes, these assumptions are correct. To use this library all you need to do is copy the header into your project and include it. CMake and OpenCV are only needed to build the tests and benchmarks.
