### ISSUE TITLE
readme wrong information for return type of kmeans_lloyd()

### ISSUE THREAD

**Issue by UriahHuang** [genbattle/dkm#15]
in section Usage of readme, the return type of kmeans_lloyd() should be 
std::tuple<**std::vector<**std::array<T, N>**>**, std::vector<uint32_t>>
not
std::tuple<std::array<T, N>, std::vector<uint32_t>>
which make me confuse at the first look

**Comment by genbattle** [comment]
Thanks for raising this, I'll fix this next time I push some code up.

**Comment by kam3k** [comment]
I found this error before seeing this issue was already brought up and submitted a PR: https://github.com/genbattle/dkm/pull/16

**Comment by genbattle** [comment]
PR merged. Fixed.
